### Get top 10 games
GET http://localhost:4004/odata/v4/game/Game?$top=10

### Get All Students
GET http://localhost:4004/odata/v4/game/Student

### Get a student with their favorite games
GET http://localhost:4004/odata/v4/game/Student(1)?$expand=to_favos($expand=to_game)

### Create a new student
POST http://localhost:4004/odata/v4/game/Student
Content-Type: application/json

{
  "First_name": "John",
  "Last_name": "Doe"
}

### Create a new favorite game for a student
POST http://localhost:4004/odata/v4/game/FavoriteGame
Content-Type: application/json

{
  "Game_ID": 1,
  "Student_ID": 2
}

### Update a student with their favorite games
PATCH http://localhost:4004/odata/v4/game/Student(1)
Content-Type: application/json

{
  "First_name": "Tom2",
  "Last_name": "Antjon2",
  "to_favos": [
    {
      "Game_ID": 1,
      "Student_ID": 1
    },
    {
      "Game_ID": 2,
      "Student_ID": 1
    }
  ]
}

### Try to delete a game
DELETE http://localhost:4004/odata/v4/game/Game(1)

